"""Analysis of tine-EP recordings (jRhodes3d, DI from the harp).

The koto machinery applies with one Rhodes-specific twist: the measured
partials are *exact harmonics* of f0 (they are generated by the pickup's
memoryless nonlinearity acting on the near-sinusoidal tine motion, so
they cannot be inharmonic). `find_partials`' free (f0, B) fit mislocks
on loud takes where harmonic 2/3 rival the fundamental (probe: B3v1
fitted -6.8c with B=1.9e-3, all partials '+9c'); we therefore snap to a
forced-harmonic grid: robust f0 from the strong partials, B := 0,
re-assign n = round(freq/f0), drop anything >20 cents off-grid.

DI recording -> no room. The 'bed' profile is still measured (it picks
up preamp hiss and sustain-skirt leakage) but the calibrator gates it;
the thump bands carry the hammer/key thunk.
"""

from __future__ import annotations

import json
import math

import numpy as np
from scipy.signal import stft, get_window

from lab.audio import find_onset, load_mono
from lab.metrics import STFT_HOP_S, STFT_WIN_S
from lab.notes import midi_to_freq, name_to_midi
from lab.partials import (
    envelope_window,
    find_partials,
    fit_double_decay,
    partial_envelope,
)

BAND_EDGES = np.geomspace(40.0, 8000.0, 11)

MAX_PARTIALS = 24
TAU_SLOW_CAP = 12.0

THUMP_WIN_S = 0.08
BED_LO_S, BED_HI_S = 0.5, 2.0
SLOPE_LO_S, SLOPE_HI_S = 0.4, 2.5


def snap_harmonic(f0_fit: float, partials: list[dict]) -> tuple[float, list[dict]]:
    """Force the partial list onto an exact harmonic grid (B = 0)."""
    if not partials:
        return f0_fit, []
    amax = max(p["amp"] for p in partials)
    # robust f0 from strong partials whose ratio is near-integer
    est = []
    for p in partials:
        r = p["freq"] / f0_fit
        n = int(round(r))
        if n < 1:
            continue
        cents = 1200 * math.log2(r / n)
        if p["amp"] >= amax * 10 ** (-45 / 20) and abs(cents) < 25:
            est.append(p["freq"] / n)
    f0 = float(np.median(est)) if est else f0_fit
    by_n: dict[int, dict] = {}
    for p in partials:
        n = int(round(p["freq"] / f0))
        if n < 1:
            continue
        cents = 1200 * math.log2(p["freq"] / (n * f0))
        if abs(cents) > 20:
            continue
        if n not in by_n or p["amp"] > by_n[n]["amp"]:
            by_n[n] = {"n": n, "freq": p["freq"], "amp": p["amp"]}
    return f0, [by_n[n] for n in sorted(by_n)]


def fit_env_ls(t: np.ndarray, env: np.ndarray, floor_db: float,
               t_min: float = 0.03):
    """Double-exp fit WITHOUT t=0 extrapolation.

    Rhodes envelopes bloom (fundamental peaks seconds in) and beat;
    `fit_double_decay`'s anchor-at-argmax + extrapolate-to-t0 inflates
    amplitudes by 8-22 dB there (probe_rhodes_fit.py) and the summed
    attack then eats the whole render's gain normalization. Instead:
    take the taus from the robust piecewise fit, then re-solve the two
    amplitudes by relative-error NNLS over the entire valid envelope —
    levels are anchored where the data is, bloom becomes a balanced
    compromise (the engine cannot rise), nothing explodes.
    """
    from scipy.optimize import nnls

    # the demod moving-average is still settling before ~1.5 windows —
    # those rising samples are tiny and, under relative-error weights,
    # would dominate the LS and crush the amplitudes (iter-3 lesson).
    grown = t >= t_min
    if grown.sum() < 8:
        return None
    t, env = t[grown], env[grown]
    fit = fit_double_decay(t, env, floor_db=floor_db)
    if fit is None:
        return None

    t_pk = float(t[int(np.argmax(env))]) - float(t[0])
    span = float(t[-1]) - float(t[0])
    if True:  # iter-6: bloomer NNLS flat-hold overshoots the tail and
        # scored worse than the capped classic fit even on bloomers
        # (E2v5 1.69 vs 1.39) — classic path for everything, with the
        # settle exclusion above (median 0.531 -> 0.509) kept.
        # normal decaying envelope: the iter-1 path (robust piecewise fit,
        # argmax anchor, woodblock-style amplitude caps) beat every NNLS
        # variant on these — keep it.
        env_max = float(env.max())
        from lab.partials import DecayFit
        return DecayFit(a_fast=min(fit.a_fast, 2.2 * env_max),
                        tau_fast=fit.tau_fast,
                        a_slow=min(fit.a_slow, 1.3 * env_max),
                        tau_slow=fit.tau_slow, rmse_db=fit.rmse_db)

    # bloomer (pickup-nonlinearity relaxation: envelope peaks late):
    # extrapolating the post-peak fit to t=0 inflates 8-22 dB. Refit
    # amplitudes by relative-error NNLS over log-spaced samples (one
    # vote per time-decade) on a basis of the fitted post-peak tau plus
    # a near-flat component so the late bloom keeps its level.
    t1 = max(min(fit.tau_slow, TAU_SLOW_CAP), 1e-4)
    t2 = TAU_SLOW_CAP
    lo = float(t[0]) + 1e-4
    hi = float(t[-1])
    if hi <= lo:
        return fit
    targets = np.geomspace(lo, hi, 96)
    idx = np.unique(np.searchsorted(t, targets).clip(0, len(t) - 1))
    ts, es = t[idx], env[idx]
    b1 = np.exp(-ts / t1)
    b2 = np.exp(-ts / t2)
    w = 1.0 / np.maximum(es, env.max() * 10 ** (floor_db / 20))
    A = np.stack([b1 * w, b2 * w], axis=1)
    try:
        (a1, a2), _ = nnls(A, es * w)
    except Exception:
        return fit
    cap = 1.5 * float(env.max())
    a1, a2 = min(a1, cap), min(a2, cap)
    model = a1 * b1 + a2 * b2
    rmse = float(np.sqrt(np.mean(
        (20 * np.log10((model + 1e-12) / (es + 1e-12))) ** 2)))
    from lab.partials import DecayFit
    return DecayFit(a_fast=float(a1), tau_fast=float(t1),
                    a_slow=float(a2), tau_slow=float(t2), rmse_db=rmse)


def bed_thump_profile(x: np.ndarray, sr: int, f0: float,
                      partial_freqs: list[float]) -> dict:
    nper = int(STFT_WIN_S * sr)
    nover = nper - int(STFT_HOP_S * sr)
    f, t, Z = stft(x, sr, nperseg=nper, noverlap=nover, padded=False)
    A = np.abs(Z)
    binw = f[1] - f[0]

    pf = np.asarray(partial_freqs, float)
    if len(pf):
        dist = np.min(np.abs(f[:, None] - pf[None, :]), axis=1)
    else:
        dist = np.full(len(f), 1e9)
    guard = max(1.5 * binw, 0.15 * f0)
    non_partial = dist > guard

    T = t[-1] if len(t) else 0.0
    thump_sel = t < THUMP_WIN_S
    bed_sel = (t >= BED_LO_S) & (t <= min(BED_HI_S, 0.8 * T))
    slope_sel = (t >= SLOPE_LO_S) & (t <= min(SLOPE_HI_S, 0.9 * T))

    thump_db, thump_tau, bed_db, bed_t60 = [], [], [], []
    for i in range(len(BAND_EDGES) - 1):
        sel = (f >= BAND_EDGES[i]) & (f < BAND_EDGES[i + 1]) & non_partial
        if sel.sum() < 2:
            thump_db.append(None)
            thump_tau.append(None)
            bed_db.append(None)
            bed_t60.append(None)
            continue
        med = np.median(A[sel], axis=0)
        tv = float(med[thump_sel].max()) if thump_sel.any() else 0.0
        bv = float(np.median(med[bed_sel])) if bed_sel.any() else 0.0
        thump_db.append(round(20 * math.log10(tv + 1e-12), 2))
        bed_db.append(round(20 * math.log10(bv + 1e-12), 2))
        k0 = int(np.argmax(med[thump_sel])) if thump_sel.any() else 0
        tsel = (t >= t[k0]) & (t <= 0.15)
        if tsel.sum() > 4:
            ts = t[tsel]
            ds = 20 * np.log10(med[tsel] + 1e-12)
            A_ = np.stack([ts, np.ones_like(ts)], axis=1)
            coef, *_ = np.linalg.lstsq(A_, ds, rcond=None)
            slope = coef[0]
            tau = -8.686 / slope if slope < -30.0 else 0.12
            thump_tau.append(round(float(np.clip(tau, 0.004, 0.12)), 4))
        else:
            thump_tau.append(None)
        if slope_sel.sum() > 6:
            ts = t[slope_sel]
            ds = 20 * np.log10(med[slope_sel] + 1e-12)
            A_ = np.stack([ts, np.ones_like(ts)], axis=1)
            coef, *_ = np.linalg.lstsq(A_, ds, rcond=None)
            slope = coef[0]
            t60 = 60.0 / -slope if slope < -1.0 else 30.0
            bed_t60.append(round(float(np.clip(t60, 0.2, 30.0)), 2))
        else:
            bed_t60.append(None)
    return {"thump_db": thump_db, "thump_tau": thump_tau,
            "bed_db": bed_db, "bed_t60": bed_t60,
            "bed_anchor_s": round(0.5 * (BED_LO_S + BED_HI_S), 2)}


def analyze_note(path: str, note: str) -> dict:
    x, sr = load_mono(path)
    onset = find_onset(x, sr)
    xo = x[onset:]
    peak_abs = float(np.max(np.abs(x)) + 1e-20)
    midi = name_to_midi(note)
    f0_nom = midi_to_freq(midi)

    f0_fit, _B, raw = find_partials(xo, sr, f0_nom, max_partials=MAX_PARTIALS)
    f0, partials = snap_harmonic(f0_fit, raw)

    results = []
    for p in partials:
        n = p["n"]
        win = envelope_window(sr, f0, f0=f0)
        t, env = partial_envelope(xo, sr, p["freq"], hop=0.005,
                                  win_samples=win)
        _, env_noise = partial_envelope(xo, sr, p["freq"] + 0.5 * f0,
                                        hop=0.005, win_samples=win)
        noise_med = float(np.median(env_noise))
        entry = {"n": n, "freq": p["freq"], "amp": p["amp"]}
        valid = env > 2.0 * env_noise
        if n <= 2:
            valid = np.ones(len(env), bool)
        # trailing-junk guard (see vibraphone DEVLOG)
        if valid.sum() >= 10 and int(np.argmax(env)) > 0.4 * len(env):
            valid = np.zeros(len(env), bool)
        if valid.sum() >= 10:
            floor = max(-65.0, 20 * math.log10(
                2.5 * noise_med / (env.max() + 1e-20) + 1e-12))
            fit = fit_env_ls(t[valid], env[valid], floor_db=floor,
                             t_min=1.5 * win / sr)
            if fit is not None:
                entry.update({
                    "a_fast": fit.a_fast / peak_abs, "tau_fast": fit.tau_fast,
                    "a_slow": fit.a_slow / peak_abs,
                    "tau_slow": min(fit.tau_slow, TAU_SLOW_CAP),
                    "fit_rmse_db": fit.rmse_db,
                    "snr": float(env.max() / (noise_med + 1e-20)),
                })
        results.append(entry)

    profile = bed_thump_profile(xo, sr, f0, [p["freq"] for p in partials])

    hop = int(0.005 * sr)
    nfr = len(xo) // hop
    fr = xo[: nfr * hop].reshape(nfr, hop)
    rms = np.sqrt((fr ** 2).mean(axis=1) + 1e-20)

    seg = xo[: int(0.15 * sr)]
    w = get_window("hann", len(seg))
    mag = np.abs(np.fft.rfft(seg * w))
    fax = np.fft.rfftfreq(len(seg), 1 / sr)
    centroid = float((mag * fax).sum() / (mag.sum() + 1e-20))

    return {
        "note": note,
        "midi": midi,
        "sr": sr,
        "duration": len(x) / sr,
        "onset_s": onset / sr,
        "f0_nominal": f0_nom,
        "f0": f0,
        "B": 0.0,
        "n_partials": len(results),
        "peak_abs": peak_abs,
        "rms_max": float(rms.max()),
        "centroid_150ms": centroid,
        "thump_db": profile["thump_db"],
        "thump_tau": profile["thump_tau"],
        "bed_db": profile["bed_db"],
        "bed_t60": profile["bed_t60"],
        "bed_anchor_s": profile["bed_anchor_s"],
        "partials": results,
        "rms_env_hop_s": 0.005,
        "rms_env_db": [round(float(20 * np.log10(v / (rms.max() + 1e-20) + 1e-12)), 2)
                       for v in rms[:1600]],
    }


def analyze_to_json(path: str, note: str, out_path: str) -> dict:
    res = analyze_note(path, note)
    with open(out_path, "w") as f:
        json.dump(res, f)
    return res
